
(function($,Edge,compId){var Composition=Edge.Composition,Symbol=Edge.Symbol;
//Edge symbol: 'stage'
(function(symbolName){Symbol.bindElementAction(compId,symbolName,"${_Rectangle}","click",function(sym,e){var myQuotes=new Array();myQuotes[0]="Sometimes I lose my thought of train.";myQuotes[1]="I need the good stuff. That Additional Marijuana.";myQuotes[2]="He said 'dingleberry' but I don't know what that shit is...some military term.";myQuotes[3]="Oh hell no. I would put my Mother in an Old Folks Home.  Angel too.  I already told his ass that.";myQuotes[4]="He got Chipmunk Teef.";myQuotes[5]="I think she's working at Fish Bones.";myQuotes[5]="She's getting ready to graduate. The's she's going for her Doctrins.";myQuotes[6]="I would just click my fingers and my Dad would say How High?";myQuotes[7]="I'm getting ready to put a chicken bunion cube in it.";myQuotes[8]="[That man's son] was always ugly!";myQuotes[9]="We just need to stick to our bread and water.";myQuotes[10]="You know I'm like Wikipedia-75% of the sh*t that comes out of my mouth is true and the other 25%...you never know where that sh*t comes from.";myQuotes[11]="She's on it like rice on water!";myQuotes[12]="Take your drugs bitches.  I need you to have a clear head.";myQuotes[13]="Danielle is at the bottom of the Tadpole.";var myRandom=Math.floor(Math.random()*myQuotes.length);sym.$("Text").html(myQuotes[myRandom]);sym.play("animate");});
//Edge binding end
Symbol.bindTriggerAction(compId,symbolName,"Default Timeline",250,function(sym,e){sym.stop();});
//Edge binding end
Symbol.bindTriggerAction(compId,symbolName,"Default Timeline",500,function(sym,e){sym.play("animate");});
//Edge binding end
Symbol.bindElementAction(compId,symbolName,"${_Group}","click",function(sym,e){var myQuotes=new Array();myQuotes[0]="Sometimes I lose my thought of train.";myQuotes[1]="I need the good stuff. That Additional Marijuana.";myQuotes[2]="He said 'dingleberry' but I don't know what that $@!* is...some military term.";myQuotes[3]="Oh hell no. I would put my Mother in an Old Folks Home.  Angel too.  I already told his @$$ that.";myQuotes[4]="He got Chipmunk Teef.";myQuotes[5]="I think she's working at Fish Bones.";myQuotes[5]="She's getting ready to graduate. The's she's going for her Doctrins.";myQuotes[6]="I would just click my fingers and my Dad would say How High?";myQuotes[7]="I'm getting ready to put a chicken bunion cube in it.";myQuotes[8]="[That man's son] was always ugly!";myQuotes[9]="We just need to stick to our bread and water.";myQuotes[10]="You know I'm like Wikipedia-75% of the $@!& that comes out of my mouth is true and the other 25%...you never know where that $@*! comes from.";myQuotes[11]="She's on it like rice on water!";myQuotes[12]="Take your drugs b$#@%!$. I need you to have a clear head.";myQuotes[13]="Danielle is at the bottom of the Tadpole.";myQuotes[13]="I need more Construction Criticism.";myQuotes[14]="Hey Gigi, what's your name?";myQuotes[15]="Winner Winner...Chicken Little.";myQuotes[16]="Let me show you how one back scratches the other back.";myQuotes[17]="It's like the blind people walking with the blind people.";var myRandom=Math.floor(Math.random()*myQuotes.length);sym.$("Text").html(myQuotes[myRandom]);sym.play("animate");});
//Edge binding end
})("stage");
//Edge symbol end:'stage'
})(jQuery,AdobeEdge,"EDGE-104795071");